name: admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  adaptive_theme: ^3.7.0
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  http: ^1.3.0
  lottie: ^3.3.1
  page_transition: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/lottie/
